apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: quarkus-deploy
spec:
  resources:
    - name: app-git
      type: git
    - name: app-image
      type: image
  params:
    - name: deploymentConfig
      description: The application name i.e. OpenShift/Kubernetes Deployment name
    - name: applicationSrcDir
      description: The source directory of the application within the source repository
  tasks:
    - name: build
      taskRef:
        name: quarkus-native
      params:
        - name: tlsVerify
          value: "false"
        - name: contextDir
          value: "${params.applicationSrcDir}"
      resources:
        inputs:
          - name: source
            resource: app-git
        outputs:
          - name: image
            resource: app-image
    - name: deploy
      taskRef:
        name: openshift-client
      runAfter:
        - build
      params:
        - name: ARGS
          value: "rollout latest ${params.deploymentConfig}"